### ISSUE TITLE
[Question]  How to use libfaketime with py.test

### ISSUE THREAD

**Issue by fuzzyweapon** [simon-weber/python-libfaketime#5]
Heya.

I'm using py.test and setup a simple test to see if I could use faketimelib with py.test.  Instead of creating application code to test against (since I started having problems), I simplified my experiment to importing a variable in from a .py I use to store my "constants", which is simply a datetime instance I want to re-use.  I passed this into the `@fake_time` decorator.

1)  At first I put the reexec statement in main body of the test module as instructed by documentation
This caused py.test to not be able to collect /any/ tests.  This doesn't seem right to me since py.test, as far as I know, uses standard test discovery.

Questions, Conclusions:
Based on suspiciously shallow logic, it would follow that, because you used unittest in your tests and they are currently passing, why would this stump py.test which also uses standard test discovery?

This suggests that a bit more work needs to be done to attain better interoperability (somewhere, py.test or python-libfaketime). 

2)  I then put the reexec statement into a module level setup function that the latest py.test version supplies.
This caused the process to ultimately terminate when it reached a `@faketime` wrapped test.
This was very weird since it tanked py.test mid-process without any error thrown.

> ============================= test session starts ==============================
> platform darwin -- Python 2.7.9, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
> django settings: config.settings (from ini file)
> rootdir: /redacted, inifile: pytest.ini
> plugins: django-2.9.1
> collected 6 items

> ../../../../redacted/q1/metrics/test_version.py s
> Test ignored.
> Process finished with exit code 0

Note that 6 items were collected (I expected three to actually execute, two passing tests and one faketime test that should have passed (even tested by simply `assert FAKE_DATE == FAKE_DATE`), but it only got to the point of ignoring one test before it fell over (obviously execution order dependent, but this one demos what I wanted).

Thoughts?
For next steps, I think this would require deep-diving even more into py.test, though I thought I'd shout out here in case there's something you can think of that would cause this and point me in the right direction.

**Comment by simon-weber** [comment]
Hi! Thanks for the detailed issue; I wish everyone was so thoughtful when opening them!

A "datetime instance I want to re-use" jumps out at me. Since python-libfaketime doesn't patch existing datetime instances you'll need to recall eg `datetime.datetime.now()` before seeing a faked time.¹

That's an easy fix, though, and probably orthogonal to the py.test issues. I'm not too familiar with the framework or its inner workings, but it's possible that faking the time confuses it (eg maybe it's timing your tests from another thread, causing it to see a faked time?). Can you paste a small example to reproduce the problems? I'll have time this weekend to dig into it if you don't crack it first.

You could also try subbing in [freezegun](https://github.com/spulec/freezegun). If it doesn't have the same problem that'll give us some information (or maybe you found this library first and aren't in need of the speed tradeoff -- I wouldn't be offended if you wanted to use it instead, haha).

¹ this is a large part of the reason why python-libfaketime is faster than freezegun. Check out [this issue](https://github.com/spulec/freezegun/issues/69) for more details, which also has ideas on [doing patching more quickly in freezegun](https://github.com/spulec/freezegun/issues/69#issuecomment-87454297).

**Comment by canassa** [comment]
@fuzzyweapon I am using python-libfaketime with py.test, what worked for me was moving the `reexec_if_needed` call to inside the py.test `pytest_configure` hook. In order to do that, just add this function to your conftest.py file:

```python
from libfaketime import reexec_if_needed

def pytest_configure():
    reexec_if_needed()

```

I hope it helps!

**Comment by simon-weber** [comment]
Nice, that looks straightforward. I'll add it to the readme. Thanks!
