### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by guettli** [simon-weber/python-libfaketime#62]
Your library looks good, and I would love to use it, ....

BUT it uses the GPL.

This means for me, that I must not use the library.

Why not LGPL/BSD/MIT?

**Comment by simon-weber** [comment]
I'm not an expert on licensing, but my thinking was that since the underlying libfaketime uses GPL my wrapper needs to as well.

It does look like there's openness to changing that in https://github.com/wolfcw/libfaketime/issues/253. If it did, I'd happily look into changing my license to something more permissible as well.

**Comment by guettli** [comment]
Sorry, I must not use GPL software. I will use this: https://github.com/spulec/freezegun/
